Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School.Data;
using School.Models;

namespace School.Controllers
{
    public class CoursesController : Controller
    {
        private readonly SchoolDbContext _context;

        public CoursesController(SchoolDbContext context)
        {
            _context = context;
        }

        //Get all courses
        public async Task<IActionResult> Index()
        {
            return View(await _context.Courses.ToListAsync());
        }
        //GET: update CourseName
        public async Task<IActionResult> UpdateCourseName()
        {
            var updateCourse = _context.Courses.FirstOrDefault(c => c.CourseId == 2);
            return View(updateCourse);
        }

        //POST: update CourseName
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateCourseName(string CourseName)
        {
            var courseToUpdate = await _context.Courses.FirstOrDefaultAsync(e => e.CourseId == 2);
            if (courseToUpdate != null)
            {
                courseToUpdate.CourseName = CourseName;
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/EnrollmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School.Data;
using School.Models;

namespace School.Controllers
{
    public class EnrollmentsController : Controller
    {
        private readonly SchoolDbContext _context;

        public EnrollmentsController(SchoolDbContext context)
        {
            _context = context;
        }

        //Get all enrollments
        public async Task<IActionResult> Index()
        {
            var enrollmentsList = _context.Enrollments
                .Include(e => e.Course)
                .OrderBy(e => e.Course)
                .Include(e => e.Student)
                .Include(e => e.Teacher)
                .ToListAsync();

            return View(await enrollmentsList);
        }
        //Get teachers for programming 1
        public async Task<IActionResult> GetTeachers()
        {
            var teachersList = _context.Enrollments
                .Include(e => e.Teacher)
                .Include(e => e.Course)
                .Where(e => e.FKCourseId == 1)
                .ToListAsync();

            return View(await teachersList);
        }
        //Get students and their teachers
        public async Task<IActionResult> GetStudentAndTeacher()
        {
            var studentTeacherList = _context.Enrollments
                .Include(e => e.Teacher)
                .Include(e => e.Student)
                .Include(e => e.Course)
                .ToListAsync();

            return View(await studentTeacherList);
        }
        //Get students and teachers for programming 1
        public async Task<IActionResult> GetStudentAndCourse()
        {
            var studentTeacherList = _context.Enrollments
                .Include(c => c.Teacher)
                .Include(c => c.Student)
                .Include(c => c.Course)
                .Where(c => c.FKCourseId == 1)
                .ToListAsync();

            return View(await studentTeacherList);
        }
        //GET: Update a students teacher in Programming 1
        public async Task<IActionResult> UpdateTeacher()
        {
            var studentTeacherList = _context.Enrollments
                .Include(e => e.Teacher)
                .Include(e => e.Student)
                .Include(e => e.Course)
                .Where(e => e.FKCourseId == 1)
                .ToList();

            var teachers = _context.Teachers.ToList();

            var viewModel = new StudentTeacherViewModel
            {
                Enrollments = studentTeacherList,
                Teachers = teachers,
            };
            return View(viewModel);
        }

        //POST: Update a students teacher in Programming 1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateTeacher(int FKStudentId, int selectedTeacher)
        {
            var enrollmentToUpdate = await _context.Enrollments
                .FirstOrDefaultAsync(e => e.FKStudentId == FKStudentId);
            if (enrollmentToUpdate != null)
            {
                enrollmentToUpdate.FKTeacherId = selectedTeacher;
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School.Data;
using School.Models;

namespace School.Controllers
{
    public class StudentsController : Controller
    {
        private readonly SchoolDbContext _context;

        public StudentsController(SchoolDbContext context)
        {
            _context = context;
        }
        //Get students
        public async Task<IActionResult> Index()
        {
            var studentsList = _context.Students.Include(s => s.StudentClass).OrderBy(s => s.StudentClass);
            return View(await studentsList.ToListAsync());
        }
    }
}

Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School.Data;
using School.Models;

namespace School.Controllers
{
    public class TeachersController : Controller
    {
        private readonly SchoolDbContext _context;

        public TeachersController(SchoolDbContext context)
        {
            _context = context;
        }
        //Get Teachers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Teachers.ToListAsync());
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - School</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/School.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Hem</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Elever</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teachers" asp-action="Index">Lärare</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">Kurser</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Enrollments" asp-action="Index">Kursregistreringar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Enrollments" asp-action="GetTeachers">Hämta lärare för Programmering 1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Enrollments" asp-action="GetStudentAndTeacher">Hämta elever med deras lärare</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Enrollments" asp-action="GetStudentAndCourse">Hämta elever och lärare i Programmering 1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Enrollments" asp-action="UpdateTeacher">Uppdatera lärare för elev i programmering 1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="UpdateCourseName">Uppdatera kursnamn på Programmering 2</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - School - Felicia Müller .NET23
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>